extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http: 
        endpoint: $HOST_IP:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "node-exporter"
          scrape_interval: 5s
          static_configs:
            - targets: ["node-exporter:9100"]
        
        - job_name: "da_exporter"
          scrape_interval: 1m
          scrape_timeout: 30s
          metrics_path: /probe
          params:
            script: [celestia_node]
            prefix: [script]
            params: [target]
            output: [stdout]
          static_configs:
            - targets: 
              - da_exporter
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - target_label: __address__
              replacement: da_exporter:9469

        - job_name: "da_exporter_metrics"
          metrics_path: /metrics
          static_configs:
            - targets: 
              - da_exporter:9469

processors:
  batch:

exporters:
   prometheus:
     endpoint: 0.0.0.0:8889

   otlphttp:
     endpoint: http://otel.celestia.tools:4318

   logging:
     verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp,prometheus]
      processors: [batch]
      exporters: [prometheus,otlphttp,logging]

  extensions: [health_check, pprof, zpages]
